name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libsodium-dev

    - name: Install R dependencies
      run: |
        Rscript -e "install.packages('rsconnect', repos = 'https://cloud.r-project.org', dependencies = TRUE)"
        Rscript -e "if (file.exists('DESCRIPTION')) devtools::install_deps(dependencies = TRUE)"

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_ACCOUNT_NAME: 'felix-riede'
        SHINYAPPS_TOKEN: ${{ secrets.TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SECRET }}
      run: |
        Rscript -e "rsconnect::setAccountInfo(name = Sys.getenv('SHINYAPPS_ACCOUNT_NAME'), token = Sys.getenv('SHINYAPPS_TOKEN'), secret = Sys.getenv('SHINYAPPS_SECRET'))"
        Rscript -e "rsconnect::deployApp(appDir = './2_scripts/', appName = 'LSTbase', account = Sys.getenv('SHINYAPPS_ACCOUNT_NAME'))"
